[package]
name = "contracts"
version = "0.1.0"
authors = ["developreuche <developeruche@gmail.com>"]
edition = "2021"

[dependencies]
ink = { version = "4.2.1", default-features = false }

openbrush = { git = "https://github.com/727-Ventures/openbrush-contracts", version = "4.0.0-beta.1", default-features = false, features = ["psp22","ownable","access_control", "psp34", "reentrancy_guard", "pausable"] }
psp22_lp =  { path = "contracts/modules/psp22_lp", default-features = false }
staking_reward =  { path = "contracts/modules/staking_reward", default-features = false }
global = {path = "contracts", default-features = false}
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
ink_e2e = "4.2.0"

[lib]
path = "contracts.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",

      "openbrush/std",
]
ink-as-dependency = []
e2e-tests = []
