[package]
name = "vesting"
version = "5.1.0"
authors = ["Use Ink <ink@use.ink>"]
edition = "2021"

[dependencies]
ink = { version = "5.1.0", default-features = false }

[dev-dependencies]

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std", 
]
ink-as-dependency = []

