[package]
name = "event-def-unused"
authors = ["Use Ink <ink@use.ink>"]
version = "0.1.0"
edition = "2021"

[dependencies]
ink = { version = "6.0.0-alpha", default-features = false, features = ["unstable-hostfn"] }  

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
]
