[package]
name = "event-def-unused"
authors = ["Use Ink <ink@use.ink>"]
version = "0.1.0"
edition = "2024"

[dependencies]
ink = { git = "https://github.com/use-ink/ink", tag = "v6.0.0-alpha.4", default-features = false }

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
]

[package.metadata.ink-lang]
abi = "ink"
